/////////////////////////////////////////////////////////////////////////////// 
// Copyright (C) 2002-2018, Open Design Alliance (the "Alliance"). 
// All rights reserved. 
// 
// This software and its documentation and related materials are owned by 
// the Alliance. The software may only be incorporated into application 
// programs owned by members of the Alliance, subject to a signed 
// Membership Agreement and Supplemental Software License Agreement with the
// Alliance. The structure and organization of this software are the valuable  
// trade secrets of the Alliance and its suppliers. The software is also 
// protected by copyright law and international treaty provisions. Application  
// programs incorporating this software must include the following statement 
// with their copyright notices:
//   
//   This application incorporates Teigha(R) software pursuant to a license 
//   agreement with Open Design Alliance.
//   Teigha(R) Copyright (C) 2002-2018 by Open Design Alliance. 
//   All rights reserved.
//
// By use of this software, its documentation or related materials, you 
// acknowledge and accept the above terms.
///////////////////////////////////////////////////////////////////////////////
//
// PathEntryDefs.h
//

#ifndef PATH_ENTRY
#error "PATH_ENTRY declaration is missing."
#endif

#define PATH_ENTRY_EX(path, enKey, func) \
  PATH_ENTRY("MetafileAdded/MetafileData" path, MetafileAdded_MetafileData##enKey, func) \
  PATH_ENTRY("BackgroundChanged/MetafileData" path, BackgroundChanged_MetafileData##enKey, func)

///////////////////////////////////////////////////////////////////////////////

  PATH_ENTRY("TextureAdded", TextureAdded, func_Level)
    PATH_ENTRY("TextureAdded/TextureID", TextureAdded_TextureID, func_Id)
    PATH_ENTRY("TextureAdded/Type", TextureAdded_Type, func_UInt32)
    PATH_ENTRY("TextureAdded/Smooth", TextureAdded_Smooth, func_Boolean)
    PATH_ENTRY("TextureAdded/Modulate", TextureAdded_Modulate, func_Boolean)
    PATH_ENTRY("TextureAdded/Width", TextureAdded_Width, func_UInt32)
    PATH_ENTRY("TextureAdded/Height", TextureAdded_Height, func_UInt32)
    PATH_ENTRY("TextureAdded/ScanlineLength", TextureAdded_ScanlineLength, func_UInt32)
    PATH_ENTRY("TextureAdded/DataAlignment", TextureAdded_DataAlignment, func_UInt32)
    PATH_ENTRY("TextureAdded/TextureData", TextureAdded_TextureData, func_BinaryStream)
    PATH_ENTRY("TextureAdded/PaletteType", TextureAdded_PaletteType, func_UInt32)
    PATH_ENTRY("TextureAdded/PaletteWidth", TextureAdded_PaletteWidth, func_UInt32)
    PATH_ENTRY("TextureAdded/PaletteScanlineLength", TextureAdded_PaletteScanlineLength, func_UInt32)
    PATH_ENTRY("TextureAdded/PaletteDataAlignment", TextureAdded_PaletteDataAlignment, func_UInt32)
    PATH_ENTRY("TextureAdded/PaletteData", TextureAdded_PaletteData, func_BinaryStream)

  PATH_ENTRY("TextureDeleted", TextureDeleted, func_Level)
    PATH_ENTRY("TextureDeleted/TextureID", TextureDeleted_TextureID, func_Id)

  PATH_ENTRY("MaterialAdded", MaterialAdded, func_Level)
    PATH_ENTRY("MaterialAdded/MaterialID", MaterialAdded_MaterialID, func_Id)
    PATH_ENTRY("MaterialAdded/MaterialName", MaterialAdded_MaterialName, func_Chars)
    PATH_ENTRY("MaterialAdded/IsDefault", MaterialAdded_IsDefault, func_Boolean)
    PATH_ENTRY("MaterialAdded/AmbientColor", MaterialAdded_AmbientColor, func_Floats)
    PATH_ENTRY("MaterialAdded/ShadingAmbientColor", MaterialAdded_ShadingAmbientColor, func_Floats)
    PATH_ENTRY("MaterialAdded/DiffuseColor", MaterialAdded_DiffuseColor, func_Floats)
    PATH_ENTRY("MaterialAdded/ShadingDiffuseColor", MaterialAdded_ShadingDiffuseColor, func_Floats)
    PATH_ENTRY("MaterialAdded/SpecularColor", MaterialAdded_SpecularColor, func_Floats)
    PATH_ENTRY("MaterialAdded/ShadingSpecularColor", MaterialAdded_ShadingSpecularColor, func_Floats)
    PATH_ENTRY("MaterialAdded/EmissionColor", MaterialAdded_EmissionColor, func_Floats)
    PATH_ENTRY("MaterialAdded/ShadingEmissionColor", MaterialAdded_ShadingEmissionColor, func_Floats)
    PATH_ENTRY("MaterialAdded/BlendFactor", MaterialAdded_BlendFactor, func_Float)
    PATH_ENTRY("MaterialAdded/ShadingBlendFactor", MaterialAdded_ShadingBlendFactor, func_Float)
    PATH_ENTRY("MaterialAdded/OpacityLevel", MaterialAdded_OpacityLevel, func_Float)
    PATH_ENTRY("MaterialAdded/ShadingOpacityLevel", MaterialAdded_ShadingOpacityLevel, func_Float)
    PATH_ENTRY("MaterialAdded/SpecularPower", MaterialAdded_SpecularPower, func_Float)
    PATH_ENTRY("MaterialAdded/TextureBlend", MaterialAdded_TextureBlend, func_Float)
    PATH_ENTRY("MaterialAdded/TextureID", MaterialAdded_TextureID, func_Id)
    PATH_ENTRY("MaterialAdded/UWrapType", MaterialAdded_UWrapType, func_UInt32)
    PATH_ENTRY("MaterialAdded/VWrapType", MaterialAdded_VWrapType, func_UInt32)

  PATH_ENTRY("MaterialDeleted", MaterialDeleted, func_Level)
    PATH_ENTRY("MaterialDeleted/MaterialID", MaterialDeleted_MaterialID, func_Id)

  PATH_ENTRY("ExtentsChanged", ExtentsChanged, func_Level)
    PATH_ENTRY("ExtentsChanged/ViewportID", ExtentsChanged_ViewportID, func_Id)
    PATH_ENTRY("ExtentsChanged/OverlayID", ExtentsChanged_OverlayID, func_Id)
    PATH_ENTRY("ExtentsChanged/SceneMin", ExtentsChanged_SceneMin, func_Doubles)
    PATH_ENTRY("ExtentsChanged/SceneMax", ExtentsChanged_SceneMax, func_Doubles)
    PATH_ENTRY("ExtentsChanged/RealMin", ExtentsChanged_RealMin, func_Doubles)
    PATH_ENTRY("ExtentsChanged/RealMax", ExtentsChanged_RealMax, func_Doubles)

  PATH_ENTRY("MetafileAdded", MetafileAdded, func_Level)
    PATH_ENTRY("MetafileAdded/MetafileID", MetafileAdded_MetafileID, func_Id)
    PATH_ENTRY("MetafileAdded/OwnerID", MetafileAdded_OwnerID, func_DbStub)
    PATH_ENTRY("MetafileAdded/LayerID", MetafileAdded_LayerID, func_Id)
    PATH_ENTRY("MetafileAdded/GeneratorID", MetafileAdded_GeneratorID, func_Id)
    PATH_ENTRY("MetafileAdded/Visibility", MetafileAdded_Visibility, func_Boolean)
    PATH_ENTRY("MetafileAdded/Highlighted", MetafileAdded_Highlighted, func_Boolean)
    PATH_ENTRY("MetafileAdded/Temporary", MetafileAdded_Temporary, func_Boolean)
    PATH_ENTRY("MetafileAdded/Nested", MetafileAdded_Nested, func_Boolean)
    PATH_ENTRY("MetafileAdded/BlockRef", MetafileAdded_BlockRef, func_Boolean)
    PATH_ENTRY("MetafileAdded/Utilitary", MetafileAdded_Utilitary, func_Boolean)
    PATH_ENTRY("MetafileAdded/Sectionable", MetafileAdded_Sectionable, func_Boolean)
    PATH_ENTRY("MetafileAdded/Composite", MetafileAdded_Composite, func_Boolean)
    PATH_ENTRY("MetafileAdded/XRef", MetafileAdded_XRef, func_Boolean)
    PATH_ENTRY("MetafileAdded/Faded", MetafileAdded_Faded, func_Boolean)
    PATH_ENTRY("MetafileAdded/ExtMin", MetafileAdded_ExtMin, func_Doubles)
    PATH_ENTRY("MetafileAdded/ExtMax", MetafileAdded_ExtMax, func_Doubles)
      //parentsMetadata.push_back("MetafileAdded")) //DropMetadata

  PATH_ENTRY("MetafileHighlightingChanged", MetafileHighlightingChanged, func_Level)
    PATH_ENTRY("MetafileHighlightingChanged/MetafileID", MetafileHighlightingChanged_MetafileID, func_Id)
    PATH_ENTRY("MetafileHighlightingChanged/Highlight", MetafileHighlightingChanged_Highlight, func_Boolean)

  PATH_ENTRY("MetafileVisibilityChanged", MetafileVisibilityChanged, func_Level)
    PATH_ENTRY("MetafileVisibilityChanged/MetafileID", MetafileVisibilityChanged_MetafileID, func_Id)
    PATH_ENTRY("MetafileVisibilityChanged/Visibility", MetafileVisibilityChanged_Visibility, func_Boolean)

  PATH_ENTRY("MetafileFadingChanged", MetafileFadingChanged, func_Level)
    PATH_ENTRY("MetafileFadingChanged/MetafileID", MetafileFadingChanged_MetafileID, func_Id)
    PATH_ENTRY("MetafileFadingChanged/Fade", MetafileFadingChanged_Fade, func_Boolean)

  PATH_ENTRY("MetafileOrderChanged", MetafileOrderChanged, func_Level)
    PATH_ENTRY("MetafileOrderChanged/ViewportID", MetafileOrderChanged_ViewportID, func_Id)
    PATH_ENTRY("MetafileOrderChanged/OverlayID", MetafileOrderChanged_OverlayID, func_Id)
    PATH_ENTRY("MetafileOrderChanged/InvalidFrom", MetafileOrderChanged_InvalidFrom, func_UInt32)
    PATH_ENTRY("MetafileOrderChanged/InvalidLen", MetafileOrderChanged_InvalidLen, func_UInt32)
    PATH_ENTRY("MetafileOrderChanged/ValidLen", MetafileOrderChanged_ValidLen, func_UInt32)
    PATH_ENTRY("MetafileOrderChanged/Ordering", MetafileOrderChanged_Ordering, func_Level)
        //DropDisplayList
      PATH_ENTRY("MetafileOrderChanged/Ordering/MetafileID", MetafileOrderChanged_Ordering_MetafileID, func_Id)

  PATH_ENTRY("MetafileOrderInheritance", MetafileOrderInheritance, func_Level)
    PATH_ENTRY("MetafileOrderInheritance/ViewportID1", MetafileOrderInheritance_ViewportID1, func_Id )
    PATH_ENTRY("MetafileOrderInheritance/OverlayID", MetafileOrderInheritance_OverlayID, func_Id )
    PATH_ENTRY("MetafileOrderInheritance/ViewportID2", MetafileOrderInheritance_ViewportID2, func_Id )
      
  PATH_ENTRY("SurfaceChanged", SurfaceChanged, func_Level)
    PATH_ENTRY("SurfaceChanged/SurfaceSizeXMin", SurfaceChanged_SurfaceSizeXMin, func_Int32)
    PATH_ENTRY("SurfaceChanged/SurfaceSizeYMin", SurfaceChanged_SurfaceSizeYMin, func_Int32)
    PATH_ENTRY("SurfaceChanged/SurfaceSizeXMax", SurfaceChanged_SurfaceSizeXMax, func_Int32)
    PATH_ENTRY("SurfaceChanged/SurfaceSizeYMax", SurfaceChanged_SurfaceSizeYMax, func_Int32)
    PATH_ENTRY("SurfaceChanged/BackgroundColor", SurfaceChanged_BackgroundColor, func_UInt8RGB)
    PATH_ENTRY("SurfaceChanged/TransparentBackground", SurfaceChanged_TransparentBackground, func_Boolean)

  PATH_ENTRY("OverlayAdded", OverlayAdded, func_Level)
    PATH_ENTRY("OverlayAdded/OverlayID", OverlayAdded_OverlayID, func_Id)
    PATH_ENTRY("OverlayAdded/Flags", OverlayAdded_Flags, func_UInt16)
    PATH_ENTRY("OverlayAdded/RenderOrder", OverlayAdded_RenderOrder, func_Int16)

  PATH_ENTRY("OverlayDeleted", OverlayDeleted, func_Level)
    PATH_ENTRY("OverlayDeleted/OverlayID", OverlayDeleted_OverlayID, func_Id)

  PATH_ENTRY("OverlayVisibilityChanged", OverlayVisibilityChanged, func_Level)
    PATH_ENTRY("OverlayVisibilityChanged/OverlayID", OverlayVisibilityChanged_OverlayID, func_Id)
    PATH_ENTRY("OverlayVisibilityChanged/Visibility", OverlayVisibilityChanged_Visibility, func_Boolean)

  PATH_ENTRY("OverlayRenderOrderChanged", OverlayRenderOrderChanged, func_Level)
    PATH_ENTRY("OverlayRenderOrderChanged/OverlayID", OverlayRenderOrderChanged_OverlayID, func_Id)
    PATH_ENTRY("OverlayRenderOrderChanged/RenderOrder", OverlayRenderOrderChanged_RenderOrder, func_Int16)

  PATH_ENTRY("ViewportAdded", ViewportAdded, func_Level)
    PATH_ENTRY("ViewportAdded/ViewportID", ViewportAdded_ViewportID, func_Id)

  PATH_ENTRY("ViewportDeleted", ViewportDeleted, func_Level)
    PATH_ENTRY("ViewportDeleted/ViewportID", ViewportDeleted_ViewportID, func_Id)

  PATH_ENTRY("ViewportInserted", ViewportInserted, func_Level)
    PATH_ENTRY("ViewportInserted/ViewportID", ViewportInserted_ViewportID, func_Id)
    PATH_ENTRY("ViewportInserted/Index", ViewportInserted_Index, func_Int32)

  PATH_ENTRY("ViewportModified", ViewportModified, func_Level)
    PATH_ENTRY("ViewportModified/ViewportID", ViewportModified_ViewportID, func_Id)
    PATH_ENTRY("ViewportModified/KindOfMod", ViewportModified_KindOfMod, func_UInt32)
      //kViewportModVisibility
    PATH_ENTRY("ViewportModified/Visibility", ViewportModified_Visibility, func_Boolean)
      //kViewportModOrientation
    PATH_ENTRY("ViewportModified/ViewParams", ViewportModified_ViewParams, func_Level)
      PATH_ENTRY("ViewportModified/ViewParams/ScreenMatrix", ViewportModified_ViewParams_ScreenMatrix, func_Matrix)
      PATH_ENTRY("ViewportModified/ViewParams/ViewingMatrix", ViewportModified_ViewParams_ViewingMatrix, func_Matrix)
      PATH_ENTRY("ViewportModified/ViewParams/ProjectionMatrix", ViewportModified_ViewParams_ProjectionMatrix, func_Matrix)
      PATH_ENTRY("ViewportModified/ViewParams/CorrectionMatrix", ViewportModified_ViewParams_CorrectionMatrix, func_Matrix)
      PATH_ENTRY("ViewportModified/ViewParams/OutputMatrix", ViewportModified_ViewParams_OutputMatrix, func_Matrix)
      PATH_ENTRY("ViewportModified/ViewParams/MetafileMatrix", ViewportModified_ViewParams_MetafileMatrix, func_Matrix)
      PATH_ENTRY("ViewportModified/ViewParams/ViewPosition", ViewportModified_ViewParams_ViewPosition, func_Doubles)
      PATH_ENTRY("ViewportModified/ViewParams/ViewBasisX", ViewportModified_ViewParams_ViewBasisX, func_Doubles)
      PATH_ENTRY("ViewportModified/ViewParams/ViewBasisY", ViewportModified_ViewParams_ViewBasisY, func_Doubles)
      PATH_ENTRY("ViewportModified/ViewParams/ViewBasisZ", ViewportModified_ViewParams_ViewBasisZ, func_Doubles)
      PATH_ENTRY("ViewportModified/ViewParams/PerspectiveProjection", ViewportModified_ViewParams_PerspectiveProjection, func_Boolean)
      PATH_ENTRY("ViewportModified/ViewParams/FieldWidth", ViewportModified_ViewParams_FieldWidth, func_Double)
      PATH_ENTRY("ViewportModified/ViewParams/FieldHeight", ViewportModified_ViewParams_FieldHeight, func_Double)
      PATH_ENTRY("ViewportModified/ViewParams/LensLength", ViewportModified_ViewParams_LensLength, func_Double)
      PATH_ENTRY("ViewportModified/ViewParams/ViewTarget", ViewportModified_ViewParams_ViewTarget, func_Doubles)
      PATH_ENTRY("ViewportModified/ViewParams/FrontClip", ViewportModified_ViewParams_FrontClip, func_Boolean)
      PATH_ENTRY("ViewportModified/ViewParams/FrontClipDist", ViewportModified_ViewParams_FrontClipDist, func_Double)
      PATH_ENTRY("ViewportModified/ViewParams/BackClip", ViewportModified_ViewParams_BackClip, func_Boolean)
      PATH_ENTRY("ViewportModified/ViewParams/BackClipDist", ViewportModified_ViewParams_BackClipDist, func_Double)
      // kViewportModPersistent
    PATH_ENTRY("ViewportModified/OverallVpId", ViewportModified_OverallVpId, func_Id)
    PATH_ENTRY("ViewportModified/PSOverallViewport", ViewportModified_PSOverallViewport, func_Boolean)
    PATH_ENTRY("ViewportModified/PSModelViewport", ViewportModified_PSModelViewport, func_Boolean)
    PATH_ENTRY("ViewportModified/PSHelperViewport", ViewportModified_PSHelperViewport, func_Boolean)
      // kViewportModContextual
    PATH_ENTRY("ViewportModified/LineStyleConfig", ViewportModified_LineStyleConfig, func_UInt8RGB)
    PATH_ENTRY("ViewportModified/FadingConfig", ViewportModified_FadingConfig, func_UInt8RGB)
      // kViewportModRect
    PATH_ENTRY("ViewportModified/ScreenRect", ViewportModified_ScreenRect, func_Doubles)
      // kViewportModNrcClip
    PATH_ENTRY("ViewportModified/NNrcCounts", ViewportModified_NNrcCounts, func_UInt32)
    PATH_ENTRY("ViewportModified/NNrcPoints", ViewportModified_NNrcPoints, func_UInt32)
    PATH_ENTRY("ViewportModified/NrcCounts", ViewportModified_NrcCounts, func_Level)
      PATH_ENTRY("ViewportModified/NrcCounts/Count", ViewportModified_NrcCounts_Count, func_Int32)
    PATH_ENTRY("ViewportModified/NrcPoints", ViewportModified_NrcPoints, func_Level)
      PATH_ENTRY("ViewportModified/NrcPoints/Point", ViewportModified_NrcPoints_Point, func_Floats)
      // kViewportModLineweights
    PATH_ENTRY("ViewportModified/NLineweightEnum", ViewportModified_NLineweightEnum, func_UInt32)
    PATH_ENTRY("ViewportModified/LineweightCoef", ViewportModified_LineweightCoef, func_Double)
    PATH_ENTRY("ViewportModified/LineweightEnum", ViewportModified_LineweightEnum, func_Level)
      PATH_ENTRY("ViewportModified/LineweightEnum/NPixels", ViewportModified_LineweightEnum_NPixels, func_UInt8)
      // kViewportModShader:
    PATH_ENTRY("ViewportModified/ShaderId", ViewportModified_ShaderId, func_Id)
    PATH_ENTRY("ViewportModified/VisualStyleId", ViewportModified_VisualStyleId, func_Id)
    PATH_ENTRY("ViewportModified/DepthBuffer", ViewportModified_DepthBuffer, func_Boolean)
    PATH_ENTRY("ViewportModified/StencilBuffer", ViewportModified_StencilBuffer, func_Boolean)
    PATH_ENTRY("ViewportModified/PolygonOffset", ViewportModified_PolygonOffset, func_Boolean)
    PATH_ENTRY("ViewportModified/Lighting", ViewportModified_Lighting, func_Boolean)
    PATH_ENTRY("ViewportModified/FaceNormals", ViewportModified_FaceNormals, func_Boolean)
    PATH_ENTRY("ViewportModified/FaceFillColor", ViewportModified_FaceFillColor, func_UInt8RGB)
      // kViewportModBorder
    PATH_ENTRY("ViewportModified/Border", ViewportModified_Border, func_Boolean)
    PATH_ENTRY("ViewportModified/BorderColor", ViewportModified_BorderColor, func_UInt8RGB) 
    PATH_ENTRY("ViewportModified/BorderWidth", ViewportModified_BorderWidth, func_Int32)
    PATH_ENTRY("ViewportModified/NBorderCounts", ViewportModified_NBorderCounts, func_UInt32)
    PATH_ENTRY("ViewportModified/NBorderPoints", ViewportModified_NBorderPoints, func_UInt32)
    PATH_ENTRY("ViewportModified/BorderCounts", ViewportModified_BorderCounts, func_Level)
      PATH_ENTRY("ViewportModified/BorderCounts/Count", ViewportModified_BorderCounts_Count, func_Int32)
      PATH_ENTRY("ViewportModified/BorderPoints", ViewportModified_BorderPoints, func_Level)
        PATH_ENTRY("ViewportModified/BorderPoints/Point", ViewportModified_BorderPoints_Point, func_Floats)

  PATH_ENTRY("LightsListChanged", LightsListChanged, func_Level)
    PATH_ENTRY("LightsListChanged/ViewportID", LightsListChanged_ViewportID, func_Id)
    PATH_ENTRY("LightsListChanged/AmbientLight", LightsListChanged_AmbientLight, func_Floats)
    PATH_ENTRY("LightsListChanged/DefaultLightsOn", LightsListChanged_DefaultLightsOn, func_Boolean)
    PATH_ENTRY("LightsListChanged/NLights", LightsListChanged_NLights, func_UInt32)
      PATH_ENTRY("LightsListChanged/LightsList", LightsListChanged_LightsList, func_Level)
        PATH_ENTRY("LightsListChanged/LightsList/Light", LightsListChanged_LightsList_Light, func_Level)
          PATH_ENTRY("LightsListChanged/LightsList/Light/Type", LightsListChanged_LightsList_Light_Type, func_Int32)
          PATH_ENTRY("LightsListChanged/LightsList/Light/DefLight", LightsListChanged_LightsList_Light_DefLight, func_Boolean)
          PATH_ENTRY("LightsListChanged/LightsList/Light/Position", LightsListChanged_LightsList_Light_Position, func_Doubles)
          PATH_ENTRY("LightsListChanged/LightsList/Light/Direction", LightsListChanged_LightsList_Light_Direction, func_Doubles)
          PATH_ENTRY("LightsListChanged/LightsList/Light/Color", LightsListChanged_LightsList_Light_Color, func_Floats)
          PATH_ENTRY("LightsListChanged/LightsList/Light/ConstantAttenuation", LightsListChanged_LightsList_Light_ConstantAttenuation, func_Float)
          PATH_ENTRY("LightsListChanged/LightsList/Light/LinearAttenuation", LightsListChanged_LightsList_Light_LinearAttenuation, func_Float)
          PATH_ENTRY("LightsListChanged/LightsList/Light/QuadraticAttenuation", LightsListChanged_LightsList_Light_QuadraticAttenuation, func_Float)
          PATH_ENTRY("LightsListChanged/LightsList/Light/SpotCutoff", LightsListChanged_LightsList_Light_SpotCutoff, func_Float)
          PATH_ENTRY("LightsListChanged/LightsList/Light/SpotExponent", LightsListChanged_LightsList_Light_SpotExponent, func_Float)
          PATH_ENTRY("LightsListChanged/LightsList/Light/SpecularFactor", LightsListChanged_LightsList_Light_SpecularFactor, func_Float)

  PATH_ENTRY("OverlayViewParamsOverride", OverlayViewParamsOverride, func_Level)
    PATH_ENTRY("OverlayViewParamsOverride/ViewportID", OverlayViewParamsOverride_ViewportID, func_Id)
    PATH_ENTRY("OverlayViewParamsOverride/OverlayID", OverlayViewParamsOverride_OverlayID, func_Id)
    PATH_ENTRY("OverlayViewParamsOverride/Override", OverlayViewParamsOverride_Override, func_Boolean)
    PATH_ENTRY("OverlayViewParamsOverride/ViewParams", OverlayViewParamsOverride_ViewParams, func_Level)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/ScreenMatrix", OverlayViewParamsOverride_ViewParams_ScreenMatrix, func_Matrix)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/ViewingMatrix", OverlayViewParamsOverride_ViewParams_ViewingMatrix, func_Matrix)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/ProjectionMatrix", OverlayViewParamsOverride_ViewParams_ProjectionMatrix, func_Matrix)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/CorrectionMatrix", OverlayViewParamsOverride_ViewParams_CorrectionMatrix, func_Matrix)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/OutputMatrix", OverlayViewParamsOverride_ViewParams_OutputMatrix, func_Matrix)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/MetafileMatrix", OverlayViewParamsOverride_ViewParams_MetafileMatrix, func_Matrix)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/ViewPosition", OverlayViewParamsOverride_ViewParams_ViewPosition, func_Doubles)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/ViewBasisX", OverlayViewParamsOverride_ViewParams_ViewBasisX, func_Doubles)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/ViewBasisY", OverlayViewParamsOverride_ViewParams_ViewBasisY, func_Doubles)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/ViewBasisZ", OverlayViewParamsOverride_ViewParams_ViewBasisZ, func_Doubles)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/PerspectiveProjection", OverlayViewParamsOverride_ViewParams_PerspectiveProjection, func_Boolean)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/FieldWidth", OverlayViewParamsOverride_ViewParams_FieldWidth, func_Double)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/FieldHeight", OverlayViewParamsOverride_ViewParams_FieldHeight, func_Double)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/LensLength", OverlayViewParamsOverride_ViewParams_LensLength, func_Double)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/ViewTarget", OverlayViewParamsOverride_ViewParams_ViewTarget, func_Doubles)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/FrontClip", OverlayViewParamsOverride_ViewParams_FrontClip, func_Boolean)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/FrontClipDist", OverlayViewParamsOverride_ViewParams_FrontClipDist, func_Double)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/BackClip", OverlayViewParamsOverride_ViewParams_BackClip, func_Boolean)
      PATH_ENTRY("OverlayViewParamsOverride/ViewParams/BackClipDist", OverlayViewParamsOverride_ViewParams_BackClipDist, func_Double)

  PATH_ENTRY("VisualStyleAdded", VisualStyleAdded, func_Level)
    PATH_ENTRY("VisualStyleAdded/VisualStyleID", VisualStyleAdded_VisualStyleID, func_Id)
    PATH_ENTRY("VisualStyleAdded/Type", VisualStyleAdded_Type, func_UInt32)
    PATH_ENTRY("VisualStyleAdded/Name", VisualStyleAdded_Name, func_Chars)
    PATH_ENTRY("VisualStyleAdded/Internal", VisualStyleAdded_Internal, func_Boolean)
    PATH_ENTRY("VisualStyleAdded/Temporary", VisualStyleAdded_Temporary, func_Boolean)
    PATH_ENTRY("VisualStyleAdded/NProps", VisualStyleAdded_NProps, func_UInt32)
    PATH_ENTRY("VisualStyleAdded/NPropsModified", VisualStyleAdded_NPropsModified, func_UInt32)
    PATH_ENTRY("VisualStyleAdded/Prop", VisualStyleAdded_Prop, func_Level)
    PATH_ENTRY("VisualStyleAdded/Prop/NProp", VisualStyleAdded_Prop_NProp, func_UInt32)
    PATH_ENTRY("VisualStyleAdded/Prop/PropType", VisualStyleAdded_Prop_PropType, func_UInt32)
    PATH_ENTRY("VisualStyleAdded/Prop/Set", VisualStyleAdded_Prop_Set, func_Boolean)
      PATH_ENTRY("VisualStyleAdded/Prop/BVal", VisualStyleAdded_Prop_BVal, func_Boolean)
      PATH_ENTRY("VisualStyleAdded/Prop/IVal", VisualStyleAdded_Prop_IVal, func_Int32)
      PATH_ENTRY("VisualStyleAdded/Prop/DVal", VisualStyleAdded_Prop_DVal, func_Double)
      PATH_ENTRY("VisualStyleAdded/Prop/CVal", VisualStyleAdded_Prop_CVal, func_UInt32)
      PATH_ENTRY("VisualStyleAdded/Prop/SVal", VisualStyleAdded_Prop_SVal, func_Chars)
  PATH_ENTRY("VisualStyleModified", VisualStyleModified, func_Level)
    PATH_ENTRY("VisualStyleModified/VisualStyleID", VisualStyleModified_VisualStyleID, func_Id)
    PATH_ENTRY("VisualStyleModified/Type", VisualStyleModified_Type, func_UInt32)
    PATH_ENTRY("VisualStyleModified/Name", VisualStyleModified_Name, func_Chars)
    PATH_ENTRY("VisualStyleModified/Internal", VisualStyleModified_Internal, func_Boolean)
    PATH_ENTRY("VisualStyleModified/Temporary", VisualStyleModified_Temporary, func_Boolean)
    PATH_ENTRY("VisualStyleModified/NProps", VisualStyleModified_NProps, func_UInt32)
    PATH_ENTRY("VisualStyleModified/NPropsModified", VisualStyleModified_NPropsModified, func_UInt32)
    PATH_ENTRY("VisualStyleModified/Prop", VisualStyleModified_Prop, func_Level)
    PATH_ENTRY("VisualStyleModified/Prop/NProp", VisualStyleModified_Prop_NProp, func_UInt32)
    PATH_ENTRY("VisualStyleModified/Prop/PropType", VisualStyleModified_Prop_PropType, func_UInt32)
    PATH_ENTRY("VisualStyleModified/Prop/Set", VisualStyleModified_Prop_Set, func_Boolean)
      PATH_ENTRY("VisualStyleModified/Prop/BVal", VisualStyleModified_Prop_BVal, func_Boolean)
      PATH_ENTRY("VisualStyleModified/Prop/IVal", VisualStyleModified_Prop_IVal, func_Int32)
      PATH_ENTRY("VisualStyleModified/Prop/DVal", VisualStyleModified_Prop_DVal, func_Double)
      PATH_ENTRY("VisualStyleModified/Prop/CVal", VisualStyleModified_Prop_CVal, func_UInt32)
      PATH_ENTRY("VisualStyleModified/Prop/SVal", VisualStyleModified_Prop_SVal, func_Chars)
  PATH_ENTRY("VisualStyleDeleted", VisualStyleDeleted, func_Level)
    PATH_ENTRY("VisualStyleDeleted/VisualStyleID", VisualStyleDeleted_VisualStyleID, func_Id)

  PATH_ENTRY("LayerAdded", LayerAdded, func_Level)
    PATH_ENTRY("LayerAdded/LayerID", LayerAdded_LayerID, func_Id)
      PATH_ENTRY("LayerAdded/Name", LayerAdded_Name, func_Chars)
      PATH_ENTRY("LayerAdded/OwnerID", LayerAdded_OwnerID, func_DbStub)
      PATH_ENTRY("LayerAdded/Props", LayerAdded_Props, func_UInt16)
  PATH_ENTRY("LayerModified", LayerModified, func_Level)
    PATH_ENTRY("LayerModified/LayerID", LayerModified_LayerID, func_Id)
      PATH_ENTRY("LayerModified/Name", LayerModified_Name, func_Chars)
      PATH_ENTRY("LayerModified/Props", LayerModified_Props, func_UInt16)
  PATH_ENTRY("LayerDeleted", LayerDeleted, func_Level)
    PATH_ENTRY("LayerDeleted/LayerID", LayerDeleted_LayerID, func_Id)

  PATH_ENTRY("LayerViewportPropsOverride", LayerViewportPropsOverride, func_Level )
    PATH_ENTRY("LayerViewportPropsOverride/ViewportID", LayerViewportPropsOverride_ViewportID, func_Id)
    PATH_ENTRY("LayerViewportPropsOverride/LayerID", LayerViewportPropsOverride_LayerID, func_Id)
    PATH_ENTRY("LayerViewportPropsOverride/Override", LayerViewportPropsOverride_Override, func_Boolean)
    PATH_ENTRY("LayerViewportPropsOverride/VpDepSpec", LayerViewportPropsOverride_VpDepSpec, func_Level)
    PATH_ENTRY("LayerViewportPropsOverride/VpDepSpec/Props", LayerViewportPropsOverride_VpDepSpec_Props, func_UInt16)

  PATH_ENTRY("BackgroundChanged", BackgroundChanged, func_Level)
    PATH_ENTRY("BackgroundChanged/ViewportID", BackgroundChanged_ViewportID, func_Id)
    PATH_ENTRY("BackgroundChanged/BaseProgramID", BackgroundChanged_BaseProgramID, func_Id)
    PATH_ENTRY("BackgroundChanged/Visible", BackgroundChanged_Visible, func_Boolean)
      //parentsMetadata.push_back("BackgroundChanged")) //DropMetadata

    //parentsMetadata.push_back("MetafileAdded")) //DropMetadata
    //parentsMetadata.push_back("BackgroundChanged")) //DropMetadata
    //for (OdUInt32 idx = 0) idx < parentsMetadata.size()) idx++)
    //{
    //  OdAnsiString asParent = parentsMetadata[idx] + "/MetafileData") // "MetafileAdded", "BackgroundChanged"
    PATH_ENTRY_EX(, ,func_Level)
      PATH_ENTRY_EX("/NArrays", _NArrays, func_UInt32)
      PATH_ENTRY_EX("/Array", _Array, func_Level)
        PATH_ENTRY_EX("/Array/Type", _Array_Type, func_UInt32ArrayType)
        PATH_ENTRY_EX("/Array/NData", _Array_NData, func_UInt32)
        PATH_ENTRY_EX("/Array/ArrayData", _Array_ArrayData, func_Array)
        PATH_ENTRY_EX("/Array/ArrayOffset", _Array_ArrayOffset, func_Floats)
        PATH_ENTRY_EX("/Array/Data", _Array_Data, func_Level)
          PATH_ENTRY_EX("/Array/Data/Entry", _Array_Data_Entry, func_Level)
            PATH_ENTRY_EX("/Array/Data/Entry/Marker", _Array_Data_Entry_Marker, func_UInt64)
            PATH_ENTRY_EX("/Array/Data/Entry/From", _Array_Data_Entry_From, func_UInt32)
        //ParseMetafileStream(pMetafile))
      PATH_ENTRY_EX("/MetafileStream", _MetafileStream, func_Level)
         PATH_ENTRY_EX("/MetafileStream/EnableOpt", _MetafileStream_EnableOpt, func_Level)
           PATH_ENTRY_EX("/MetafileStream/EnableOpt/Mode", _MetafileStream_EnableOpt_Mode, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/DisableOpt", _MetafileStream_DisableOpt, func_Level)
           PATH_ENTRY_EX("/MetafileStream/DisableOpt/Mode", _MetafileStream_DisableOpt_Mode, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/Color", _MetafileStream_Color, func_Level)
           PATH_ENTRY_EX("/MetafileStream/Color/Color", _MetafileStream_Color_Color, func_UInt8RGB)
         PATH_ENTRY_EX("/MetafileStream/EnableArray", _MetafileStream_EnableArray, func_Level)
           PATH_ENTRY_EX("/MetafileStream/EnableArray/Type", _MetafileStream_EnableArray_Type, func_UInt8)
           PATH_ENTRY_EX("/MetafileStream/EnableArray/NArray", _MetafileStream_EnableArray_NArray, func_UInt32)
         PATH_ENTRY_EX("/MetafileStream/DisableArray", _MetafileStream_DisableArray, func_Level)
           PATH_ENTRY_EX("/MetafileStream/DisableArray/Type", _MetafileStream_DisableArray_Type, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/DrawArrays", _MetafileStream_DrawArrays, func_Level)
           PATH_ENTRY_EX("/MetafileStream/DrawArrays/Mode", _MetafileStream_DrawArrays_Mode, func_UInt8)
           PATH_ENTRY_EX("/MetafileStream/DrawArrays/First", _MetafileStream_DrawArrays_First, func_Int32)
           PATH_ENTRY_EX("/MetafileStream/DrawArrays/Count", _MetafileStream_DrawArrays_Count, func_Int32)
         PATH_ENTRY_EX("/MetafileStream/DrawElements", _MetafileStream_DrawElements, func_Level)
           PATH_ENTRY_EX("/MetafileStream/DrawElements/Mode", _MetafileStream_DrawElements_Mode, func_UInt8)
           PATH_ENTRY_EX("/MetafileStream/DrawElements/Count", _MetafileStream_DrawElements_Count, func_Int32)
           PATH_ENTRY_EX("/MetafileStream/DrawElements/NArray", _MetafileStream_DrawElements_NArray, func_UInt32)
         PATH_ENTRY_EX("/MetafileStream/CullFace", _MetafileStream_CullFace, func_Level)
           PATH_ENTRY_EX("/MetafileStream/CullFace/Mode", _MetafileStream_CullFace_Mode, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/LStipple", _MetafileStream_LStipple, func_Level)
           PATH_ENTRY_EX("/MetafileStream/LStipple/Pattern", _MetafileStream_LStipple_Pattern, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/PStipple", _MetafileStream_PStipple, func_Level)
           PATH_ENTRY_EX("/MetafileStream/PStipple/Pattern", _MetafileStream_PStipple_Pattern, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/VPoint", _MetafileStream_VPoint, func_Level)
           PATH_ENTRY_EX("/MetafileStream/VPoint/Point", _MetafileStream_VPoint_Point, func_Floats)
         PATH_ENTRY_EX("/MetafileStream/VLine", _MetafileStream_VLine, func_Level)
           PATH_ENTRY_EX("/MetafileStream/VLine/Point1", _MetafileStream_VLine_Point1, func_Floats)
           PATH_ENTRY_EX("/MetafileStream/VLine/Point2", _MetafileStream_VLine_Point2, func_Floats)
         PATH_ENTRY_EX("/MetafileStream/IPoint", _MetafileStream_IPoint, func_Level)
           PATH_ENTRY_EX("/MetafileStream/IPoint/Index", _MetafileStream_IPoint_Index, func_Int32)
         PATH_ENTRY_EX("/MetafileStream/ILine", _MetafileStream_ILine, func_Level)
           PATH_ENTRY_EX("/MetafileStream/ILine/Index1", _MetafileStream_ILine_Index1, func_Int32)
           PATH_ENTRY_EX("/MetafileStream/ILine/Index2", _MetafileStream_ILine_Index2, func_Int32)
         PATH_ENTRY_EX("/MetafileStream/HLRStencil", _MetafileStream_HLRStencil, func_Level)
           PATH_ENTRY_EX("/MetafileStream/HLRStencil/State", _MetafileStream_HLRStencil_State, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/EnableShading", _MetafileStream_EnableShading, func_Level)
           PATH_ENTRY_EX("/MetafileStream/EnableShading/Mode", _MetafileStream_EnableShading_Mode, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/DisableShading", _MetafileStream_DisableShading, func_Level)
           PATH_ENTRY_EX("/MetafileStream/DisableShading/Mode", _MetafileStream_DisableShading_Mode, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/Material", _MetafileStream_Material, func_Level)
           PATH_ENTRY_EX("/MetafileStream/Material/MaterialID", _MetafileStream_Material_MaterialID, func_Id)
         PATH_ENTRY_EX("/MetafileStream/InitTexture", _MetafileStream_InitTexture, func_Level)
           PATH_ENTRY_EX("/MetafileStream/InitTexture/TextureID", _MetafileStream_InitTexture_TextureID, func_Id)
           PATH_ENTRY_EX("/MetafileStream/InitTexture/Repeat", _MetafileStream_InitTexture_Repeat, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/UninitTexture", _MetafileStream_UninitTexture, func_Level)
               // No data in this entry
         PATH_ENTRY_EX("/MetafileStream/SelectionMarker", _MetafileStream_SelectionMarker, func_Level)
           PATH_ENTRY_EX("/MetafileStream/SelectionMarker/Marker", _MetafileStream_SelectionMarker_Marker, func_UInt64)
         PATH_ENTRY_EX("/MetafileStream/EnableMarkerArray", _MetafileStream_EnableMarkerArray, func_Level)
           PATH_ENTRY_EX("/MetafileStream/EnableMarkerArray/Type", _MetafileStream_EnableMarkerArray_Type, func_UInt8)
           PATH_ENTRY_EX("/MetafileStream/EnableMarkerArray/NArray", _MetafileStream_EnableMarkerArray_NArray, func_UInt32)
         PATH_ENTRY_EX("/MetafileStream/DisableMarkerArray", _MetafileStream_DisableMarkerArray, func_Level)
           PATH_ENTRY_EX("/MetafileStream/DisableMarkerArray/Type", _MetafileStream_DisableMarkerArray_Type, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/SelectionFlags", _MetafileStream_SelectionFlags, func_Level)
           PATH_ENTRY_EX("/MetafileStream/SelectionFlags/Flags", _MetafileStream_SelectionFlags_Flags, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/Lineweight", _MetafileStream_Lineweight, func_Level)
           PATH_ENTRY_EX("/MetafileStream/Lineweight/Type", _MetafileStream_Lineweight_Type, func_UInt8)
           PATH_ENTRY_EX("/MetafileStream/Lineweight/Ps", _MetafileStream_Lineweight_Ps, func_Double)
           PATH_ENTRY_EX("/MetafileStream/Lineweight/Lw", _MetafileStream_Lineweight_Lw, func_Int16)
         PATH_ENTRY_EX("/MetafileStream/Program", _MetafileStream_Program, func_Level)
           PATH_ENTRY_EX("/MetafileStream/Program/ProgramID", _MetafileStream_Program_ProgramID, func_Id)
         PATH_ENTRY_EX("/MetafileStream/TtfText", _MetafileStream_TtfText, func_Level)
           PATH_ENTRY_EX("/MetafileStream/TtfText/Transform", _MetafileStream_TtfText_Transform, func_Matrix)
           PATH_ENTRY_EX("/MetafileStream/TtfText/Direction", _MetafileStream_TtfText_Direction, func_Doubles)
           PATH_ENTRY_EX("/MetafileStream/TtfText/NText", _MetafileStream_TtfText_NText, func_UInt32)
           PATH_ENTRY_EX("/MetafileStream/TtfText/Text", _MetafileStream_TtfText_Text, func_Level)
             PATH_ENTRY_EX("/MetafileStream/TtfText/Text/Char", _MetafileStream_TtfText_Text_Char, func_Level)
               PATH_ENTRY_EX("/MetafileStream/TtfText/Text/Char/MetafileID", _MetafileStream_TtfText_Text_Char_MetafileID, func_Id)
               PATH_ENTRY_EX("/MetafileStream/TtfText/Text/Char/Multiplier", _MetafileStream_TtfText_Text_Char_Multiplier, func_Double)
         PATH_ENTRY_EX("/MetafileStream/PushMatrix", _MetafileStream_PushMatrix, func_Level)
           PATH_ENTRY_EX("/MetafileStream/PushMatrix/Identity", _MetafileStream_PushMatrix_Identity, func_UInt8)
           PATH_ENTRY_EX("/MetafileStream/PushMatrix/Matrix", _MetafileStream_PushMatrix_Matrix, func_Matrix)
         PATH_ENTRY_EX("/MetafileStream/PopMatrix", _MetafileStream_PopMatrix, func_Level)
             // No data in this entry
         PATH_ENTRY_EX("/MetafileStream/Metafile", _MetafileStream_Metafile, func_Level)
           PATH_ENTRY_EX("/MetafileStream/Metafile/MetafileID", _MetafileStream_Metafile_MetafileID, func_Id)
         PATH_ENTRY_EX("/MetafileStream/GeomMarker", _MetafileStream_GeomMarker, func_Level)
           PATH_ENTRY_EX("/MetafileStream/GeomMarker/Type", _MetafileStream_GeomMarker_Type, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/MetafileMarker", _MetafileStream_MetafileMarker, func_Level)
           PATH_ENTRY_EX("/MetafileStream/MetafileMarker/Marker", _MetafileStream_MetafileMarker_Marker, func_Id)
      //SEA missinf MetafileStreamRecords
         PATH_ENTRY_EX("/MetafileStream/UserEntry", _MetafileStream_UserEntry, func_Level)
           PATH_ENTRY_EX("/MetafileStream/UserEntry/NumData", _MetafileStream_UserEntry_NumData, func_UInt32)
           PATH_ENTRY_EX("/MetafileStream/UserEntry/Data", _MetafileStream_UserEntry_Data, func_BinaryStream)
         PATH_ENTRY_EX("/MetafileStream/Linestyle", _MetafileStream_Linestyle, func_Level)
           PATH_ENTRY_EX("/MetafileStream/Linestyle/Default", _MetafileStream_Linestyle_Default, func_Boolean)
           PATH_ENTRY_EX("/MetafileStream/Linestyle/CapsType", _MetafileStream_Linestyle_CapsType, func_UInt8)
           PATH_ENTRY_EX("/MetafileStream/Linestyle/JoinType", _MetafileStream_Linestyle_JoinType, func_UInt8)
         PATH_ENTRY_EX("/MetafileStream/VisualStyle", _MetafileStream_VisualStyle, func_Level)
           PATH_ENTRY_EX("/MetafileStream/VisualStyle/VisualStyleID", _MetafileStream_VisualStyle_VisualStyleID, func_Id)


  PATH_ENTRY("MetafileDeleted", MetafileDeleted, func_Level)
    PATH_ENTRY("MetafileDeleted/MetafileID", MetafileDeleted_MetafileID, func_Id)

  PATH_ENTRY("MetafileHlBranchAttached", MetafileHlBranchAttached, func_Level)
  PATH_ENTRY("MetafileHlBranchAttached/MetafileID", MetafileHlBranchAttached_MetafileID, func_Id)
  PATH_ENTRY("MetafileHlBranchAttached/HlBranchID", MetafileHlBranchAttached_HlBranchID, func_Id)

  PATH_ENTRY("MetafileHlBranchDetached", MetafileHlBranchDetached, func_Level)
  PATH_ENTRY("MetafileHlBranchDetached/MetafileID", MetafileHlBranchDetached_MetafileID, func_Id)

  PATH_ENTRY("HlBranchAdded", HlBranchAdded, func_Level)
  PATH_ENTRY("HlBranchAdded/HlBranchID", HlBranchAdded_HlBranchID, func_Id)
  PATH_ENTRY("HlBranchAdded/OwnerID", HlBranchAdded_OwnerID, func_DbStub)
  PATH_ENTRY("HlBranchAdded/NChilds", HlBranchAdded_NChilds, func_UInt64)
  PATH_ENTRY("HlBranchAdded/NMarkers", HlBranchAdded_NMarkers, func_UInt64)
  PATH_ENTRY("HlBranchAdded/Childs", HlBranchAdded_Childs, func_Level)
  PATH_ENTRY("HlBranchAdded/Childs/HlBranchID", HlBranchAdded_Childs_HlBranchID, func_Id)
  PATH_ENTRY("HlBranchAdded/Markers", HlBranchAdded_Markers, func_Level)
  PATH_ENTRY("HlBranchAdded/Markers/Marker", HlBranchAdded_Markers_Marker, func_UInt64)


  PATH_ENTRY("HlBranchModified", HlBranchModified, func_Level)
  PATH_ENTRY("HlBranchModified/HlBranchID", HlBranchModified_HlBranchID, func_Id)
  PATH_ENTRY("HlBranchModified/NChilds", HlBranchModified_NChilds, func_UInt64)
  PATH_ENTRY("HlBranchModified/NMarkers", HlBranchModified_NMarkers, func_UInt64)
  PATH_ENTRY("HlBranchModified/Childs", HlBranchModified_Childs, func_Level)
  PATH_ENTRY("HlBranchModified/Childs/HlBranchID", HlBranchModified_Childs_HlBranchID, func_Id)
  PATH_ENTRY("HlBranchModified/Markers", HlBranchModified_Markers, func_Level)
  PATH_ENTRY("HlBranchModified/Markers/Marker", HlBranchModified_Markers_Marker, func_UInt64)

  PATH_ENTRY("HlBranchDeleted", HlBranchDeleted, func_Level)
  PATH_ENTRY("HlBranchDeleted/HlBranchID", HlBranchDeleted_HlBranchID, func_Id)
  // TODO

///////////////////////////////////////////////////////////////////////////////

#undef PATH_ENTRY_EX
#undef PATH_ENTRY
